version: '3.7'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_PASSWORD=glpi_pwd
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
    networks:
      - glpi-net

  app:
    image: glpi:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - glpi:/var/www/glpi
      - config:/etc/glpi
      - files:/var/lib/glpi
      - log:/var/log/glpi
    restart: always
    ports:
      - 80:80
    links:
      - db
    environment:
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_HOST=db
    networks:
      - glpi-net

networks:
  glpi-net:
    driver: bridge

volumes:
  glpi:
  config:
  files:
  log:
  db:
